<?php

/**
 * @file
 * Rate of CKČ short novels.
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\ckc_hodnoceni\CkcHodnoceniService;

/**
 * Implements hook_entity_insert().
 */
function ckc_hodnoceni_entity_insert(EntityInterface $entity) {
  ckc_hodnoceni_entity__clear_cache($entity);
}

/**
 * Implements hook_entity_update().
 */
function ckc_hodnoceni_entity_update(EntityInterface $entity) {
  ckc_hodnoceni_entity__clear_cache($entity);
}

/**
 * Implements hook_entity_delete().
 */
function ckc_hodnoceni_entity_delete(EntityInterface $entity) {
  ckc_hodnoceni_entity__clear_cache($entity);
}

function ckc_hodnoceni_entity__clear_cache(EntityInterface $entity) {
  if ($entity->getEntityTypeId() === 'node' && $entity->bundle() === 'povidka') {
    $cid = "ckc_hodnoceni:works:{$entity->field_rocnik_ref->entity->name->value}:{$entity->field_kategorie_ref->entity->field_kod_kategorie->value}";
    \Drupal::cache()->invalidate($cid);
  }
  if (
    $entity->getEntityTypeId() === 'taxonomy_term'
    && in_array($entity->bundle(), [CkcHodnoceniService::CKC_ROCNIK, CkcHodnoceniService::CKC_KATEGORIE])
  ) {
    $cid = "ckc_hodnoceni:taxonomy:{$entity->bundle()}";
    \Drupal::cache()->invalidate($cid);
  }
}

/**
 * Implements hook_webform_options_WEBFORM_OPTIONS_ID_alter().
 */
function ckc_hodnoceni_webform_options_ckc_kategorie_alter(array &$options, array &$element) {
  $options = CkcHodnoceniService::kategorie();
}

/**
 * Implements hook_webform_options_WEBFORM_OPTIONS_ID_alter().
 */
function ckc_hodnoceni_webform_options_ckc_prace_alter(array &$options, array &$element) {
  $year = \Drupal::routeMatch()->getParameter('ckc_rocnik');
  $category = \Drupal::routeMatch()->getParameter('ckc_kategorie');
  if (isset($year) && isset($category)) {
    $options = CkcHodnoceniService::prace($year, $category);
  } else {
    $options = ['' => ''];
  }
}

/**
 * Implements hook_webform_submission_form_alter().
 */
function ckc_hodnoceni_webform_submission_form_alter(array &$form, FormStateInterface $form_state, $form_id) {
  if ($form_id === "webform_submission_hodnotici_formular_ckc_edit_form") {
    $form['actions']['submit']['#validate'][] = 'ckc_hodnoceni_hodnotici_formular_ckc_form_submit';
  }
}

function ckc_hodnoceni_hodnotici_formular_ckc_form_submit($form, FormStateInterface $form_state) {
  if ($form_state->getValue('1_poradi_nevyhlasovat') === 1) {
    $form_state->setValue('1_poradi_1', '');
  }
}

/**
 * Implements hook_theme().
 */
function ckc_hodnoceni_theme($existing, $type, $theme, $path) {
  $themes['ckc_rate_form'] = ['render element' => 'form'];
  return $themes;
}
